### ISSUE TITLE
Open online demo fail

### ISSUE THREAD

**Issue by Tangjj1996** [vincentdchan/blocky-editor#44]
The demo link [https://blocky-editor.dev/] has unexpectedly closed the connection, maybe the domain has been expired?

**Comment by vincentdchan** [comment]
The website is hosted on Vercel. Are you blocked by the firewall?.

**Comment by vincentdchan** [comment]
I can access to it.

**Comment by Tangjj1996** [comment]
> I can access to it.
😂 Now I can access to it too when I transform clashX rule to direct, It's so strange. Maybe the domain hasn't been blocked by the GFW, anyway I can see your website, fascinating job👍.
