### ISSUE TITLE
Optional title block support

### ISSUE THREAD

**Issue by doodlewind** [vincentdchan/blocky-editor#65]
Blocky looks very promising!

I'm trying to find out if I can integrate Blocky as a simple input box component (e.g. using it in a comment section), since it's really light. But currently Blocky assumes a title block by default, while in this case title is generally not needed.

I did some quick tweaks based on current master branch, adding `hasTitle: false` config and it seems to work (https://github.com/doodlewind/blocky-editor/commit/448d376a95ba2c78886daf0daec774041e5089ac). But the behavior of enter breaks, so not sure if there is any other coupling related to `title` concept. Any ideas? Would love to see what I can do :)

**Comment by vincentdchan** [comment]
Done #73
